### ISSUE TITLE
How to run on a machine that doesn't have NVIDIA GPU but only by using CPU!!

### ISSUE THREAD

**Issue by venkateshreddy5353** [KiseKloset/KiseKloset#7]
post installation of the libraries using install.sh, while starting fast api using python src/main.py, it complains about missing dlls related to cupy(cudnn64_8.dll -> not found,,cuTENSOR.dll -> not found, nvcuda.dll -> not found)

**complete error:**

`Traceback (most recent call last):
  File "C:\Users\Venkatesh Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "C:\Users\Venkatesh Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "C:\Users\Venkatesh Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Users\Venkatesh Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\cupy\cuda\compiler.py", line 14, in <module>
    from cupy.cuda import function
  File "cupy\cuda\function.pyx", line 1, in init cupy.cuda.function
  File "cupy\_core\_carray.pyx", line 1, in init cupy._core._carray
  File "cupy\_core\internal.pyx", line 1, in init cupy._core.internal
  File "cupy\cuda\memory.pyx", line 1, in init cupy.cuda.memory
ImportError: DLL load failed while importing driver: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Easystepin\KiseKloset\src\main.py", line 14, in <module>
    from api.tryon.router import router as tryon_router
  File "D:\Easystepin\KiseKloset\src\api\tryon\router.py", line 9, in <module>
    from .service import TryonService
  File "D:\Easystepin\KiseKloset\src\api\tryon\service\__init__.py", line 9, in <module>
    from .dm_vton import DMVTON, get_transform
  File "D:\Easystepin\KiseKloset\src\api\tryon\service\dm_vton\__init__.py", line 1, in <module>
    import cupy
  File "C:\Users\Venkatesh Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: C:\ProgramData\anaconda3\Library
DLL dependencies:
  KERNEL32.dll -> C:\WINDOWS\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\WINDOWS\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> C:\Python310\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> C:\ProgramData\anaconda3\Library\bin\cublas64_11.dll
  cudart64_110.dll -> C:\ProgramData\anaconda3\Library\bin\cudart64_110.dll
  cudnn64_8.dll -> not found
  cufft64_10.dll -> C:\ProgramData\anaconda3\Library\bin\cufft64_10.dll
  curand64_10.dll -> C:\ProgramData\anaconda3\Library\bin\curand64_10.dll
  cusolver64_11.dll -> C:\ProgramData\anaconda3\Library\bin\cusolver64_11.dll
  cusparse64_11.dll -> C:\ProgramData\anaconda3\Library\bin\cusparse64_11.dll
  nvcuda.dll -> not found
  nvrtc64_112_0.dll -> C:\ProgramData\anaconda3\Library\bin\nvrtc64_112_0.dll
  python310.dll -> C:\Python310\python310.dll

Original error:
  ImportError: DLL load failed while importing driver: The specified module could not be found.
================================================================`

**Comment by zero-nnkn** [comment]
Currently, our [Virtual try-on model](https://github.com/KiseKloset/DM-VTON) can only run on GPU (because we use cuda code).
In case you really need to run on a CPU device, you need to change the try-on model (maybe use [FS-VTON](https://github.com/SenHe/Flow-Style-VTON))
